#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview, and ACC Config Server.
#

version: '2'
services:
    em:
        image: isl-dsdc.ca.com:5000/apmswat/apm-em:10.7.0-HF3
        links:
            - db:db
        ports:
            - "5001:5001"
            - "8081:8081"
            - "8444:8444"
        environment:
            - HEAP="2048m"
        volumes:
#    - ~/mm:/root/Introscope/config/modules
            - ~/git/docker-introscope/transfer/xmltv:/transfer/xmltv
            - ~/git/docker-introscope/transfer/modules:/transfer/modules

    db:
        image: isl-dsdc.ca.com:5000/apmswat/apm-postgres:10.7.0-HF3
#        ports:
#            - "5432:5432"

    webview:
        image: isl-dsdc.ca.com:5000/apmswat/apm-webview:10.7.0-HF3
        links:
            - em:em
        ports:
            - "8082:8080"

    configserver:
        image: isl-dsdc.ca.com:5000/apmswat/apm-configserver:10.7.0-HF3
        ports:
            - "8443:8443"
            - "8888:8888"
